language: node_js
before_install:
  - if [[ `npm -v` != 3* ]]; then npm i -g npm@3; fi
node_js:
  - "8"
  - "7"
  - "6"
  - "4"
env:
  - NODE_TLS_REJECT_UNAUTHORIZED=0
services:
  - elasticsearch
  - redis-server
script: "npm test"
before_script:
  - sleep 10
